
from hyfetch.distro import AsciiArt

MassOS = AsciiArt(match=""""MassOS"*""", color='7', ascii="""
${c1} -+++/+++osyyhdmNNMMMMNdy/
 /MMMMMMMMMMMMMMMMMMMMMMMMm.
 /MMMMMMMMMMMMMMMMMMMMMMMMMm
 /MMMMMMMMMMMMMMMMMMMMMMMMMM:
 :ddddddddhddddddddhdddddddd/
 /NNNNNNNm:NNNNNNNN-NNNNNNNNo
 /MMMMMMMN:MMMMMMMM-MMMMMMMMs
 /MMMMMMMN:MMMMMMMM-MMMMMMMMs
 /MMMMMMMN:MMMMMMMM-MMMMMMMMs
 /MMMMMMMN:MMMMMMMM-MMMMMMMMs
 /MMMMMMMN:MMMMMMMM-MMMMMMMMs
 /MMMMMMMN:MMMMMMMM-MMMMMMMMs
 /MMMMMMMN:MMMMMMMM-MMMMMMMMs
 /MMMMMMMN:MMMMMMMM-MMMMMMMMs
 :MMMMMMMN:MMMMMMMM-MMMMMMMMs
  dMMMMMMN:MMMMMMMM-MMMMMMMMs
  `yNMMMMN:MMMMMMMM-MMMMMMMMs
    `:+oss.ssssssss.ssssssss/
""")
    