#!/usr/bin/env bash
# vim: fdm=marker:noai:ts=4:sw=4
#
# Neofetch info about your system
# https://github.com/dylanaraps/neofetch
#
# Required Dependencies:
#   Bash 3.0+
#   xprop
#   [Linux / BSD / Windows] Uptime detection: procps or procps-ng
#
# Optional Dependencies: (You'll lose these features without them)
#   Displaying Images: w3m + w3m-img
#   Image Cropping: ImageMagick
#   Displaying song with Google Play Music: gpmdp-bash
#   [ Linux / BSD ] Wallpaper Display: feh, nitrogen or gsettings
#   [ Linux / BSD ] Current Song: mpc, cmus, moc
#   [ Linux ] Current Song: spotify
#   [ Linux / BSD ] Resolution detection: xorg-xdpyinfo
#   [ OS X ] Getting screen resolution (faster): screenresolution
#
# Created by Dylan Araps
# https://github.com/dylanaraps/

version="${BASH_VERSION/.*}"
SYS_LOCALE="${LANG:-C}"
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-${HOME}/.config}"

# Speed up script by not using unicode
export LC_ALL=C
export LANG=C

# Set no case match and extended globbing.
shopt -s nocasematch extglob


# Config Options {{{


# Info Options {{{


# Info
# See this wiki page for more info:
# https://github.com/dylanaraps/neofetch/wiki/Customizing-Info
printinfo () {
    info title
    info underline

    info "OS" distro
    info "Kernel" kernel
    info "Uptime" uptime
    info "Packages" packages
    info "Shell" shell
    info "Resolution" resolution
    info "DE" de
    info "WM" wm
    info "WM Theme" wmtheme
    info "Theme" theme
    info "Icons" icons
    info "CPU" cpu
    info "GPU" gpu
    info "Memory" memory

    # info "Font" font
    # info "Disk" disk
    # info "Battery" battery
    # info "Song" song
    # info "Local IP" localip
    # info "Public IP" publicip
    # info "Users" users
    # info "Birthday" birthday

    info linebreak
    info cols
    info linebreak
    info linebreak
}


# Kernel

# Show more kernel info
# --kernel_shorthand on/off
kernel_shorthand="on"


# Distro

# Mac OS X hide/show build version
# --osx_buildversion on/off
osx_buildversion="on"

# Mac OS X hide/show codename
# --osx_codename on/off
osx_codename="on"

# Show 'x86_64' and 'x86' in 'Distro:' output.
# --os_arch on/off
os_arch="on"


# Uptime

# Shorten the output of the uptime function
# --uptime_shorthand tiny, on, off
uptime_shorthand="off"


# Shell

# Show the path to $SHELL
# --shell_path on/off
shell_path="on"

# Show $SHELL's version
# --shell_version on/off
shell_version="off"


# CPU

# CPU speed type
# Only works on Linux with cpufreq.
# --speed_type current, min, max, bios,
# scaling_current, scaling_min, scaling_max
speed_type="max"

# CPU Display
# Set shorthand setting and progress bar setting
# --cpu_display (name, speed, tiny, on, off) (bar, infobar, barinfo, off)
cpu_shorthand="off"
cpu_display="off"

# CPU Cores
# Display CPU cores in output
# --cpu_cores on/off
cpu_cores="on"

# GPU

# Shorten output of the getgpu funcion
# --gpu_shorthand on/off/tiny
gpu_shorthand="on"

# Resolution

# Display refresh rate next to each monitor
# Unsupported on Windows
# --refresh_rate on/off
refresh_rate="off"

# Gtk Theme / Icons

# Shorten output (Hide [GTK2] etc)
# --gtk_shorthand on/off
gtk_shorthand="off"


# Enable/Disable gtk2 theme/icons output
# --gtk2 on/off
gtk2="on"

# Enable/Disable gtk3 theme/icons output
# --gtk3 on/off
gtk3="on"


# Battery

# Which battery to display.
# By default we display all batteries.
# NOTE: Only works on Linux.
# --battery_num all, 0, 1, 2, etc
battery_num="all"

# Whether or not to print each battery on the same line.
# By default each battery gets its own line and title.
# NOTE: Only works on Linux.
# --battery_shorthand on/off
battery_shorthand="off"


# IP Address

# Website to ping for the public IP
# --ip_host url
public_ip_host="http://ident.me"


# Song

# Print the Artist and Title on seperate lines
# --song_shorthand on/off
song_shorthand="off"


# Birthday

# Whether to show a long pretty output
# or a shortened one
# NOTE: Long pretty output doesn't work on OpenBSD or NetBSD.
# --birthday_shorthand on/off
birthday_shorthand="off"

# Whether to show the time in the output
# --birthday_time on/off
birthday_time="on"

# Date format to use when printing birthday
# --birthday_format "format"
birthday_format="%a %d %b %Y %l:%M %p"


# Color Blocks

# Color block range
# --block_range start end
start=0
end=7

# Toggle color blocks
# --color_blocks on/off
color_blocks="on"

# Color block width
# --color_block_width num
block_width=3


# }}}

# Text Colors {{{


# Text Colors
# Each number represents a different part of
# the text in this order:
# title, @, underline, subtitle, colon, info
# colors=(4 6 1 8 8 6)
colors=(distro)


# }}}

# Text Options {{{


# Toggle line wrapping
# --line_wrap on/off
line_wrap="off"

# Toggle bold text
# --bold on/off
bold="on"

# Enable/Disable Underline
# --underline on/off
underline_enabled="on"

# Underline character
# --underline_char char
underline_char="-"

# Prompt height
# You should only have to change this if your
# prompt is greater than 2 lines high.
# --prompt_height num
prompt_height=1


# }}}

# Progress Bars {{{


# Progress bar character
# --progress_char char
progress_char="━"

# Progress bar length in spaces
# Number of chars long to make the progress bars.
# --progress_length num
progress_length="15"

# Progress bar colors
# When set to distro, uses your distro's logo colors
# Takes: num, "distro"
# --progress_colors col col
progress_color_elapsed="distro"
progress_color_total="distro"

# Customize how the info is displayed.
# bar: Only the progress bar is displayed.
# infobar: The bar is displayed after the info.
# barinfo: The bar is displayed before the info.
# off: Only the info is displayed.
#
# --memory_display bar/infobar/barinfo/off
# --battery_display bar/infobar/barinfo/off
# --disk_display bar/infobar/barinfo/off
memory_display="off"
battery_display="off"
disk_display="off"


# }}}

# Image Options {{{


# Image Source
# --image wall, ascii, /path/to/img, /path/to/dir/, off
image="wall"

# Thumbnail directory
thumbnail_dir="$HOME/.cache/thumbnails/neofetch"

# W3m-img path
# This is automatically detected, this variable
# should only be set to w3m-img's location if the
# builtin detection doesn't work.
w3m_img_path="/usr/lib/w3m/w3mimgdisplay"

# Image position
# Only works with the w3m backend
# --image_position left/right
image_position="left"

# Crop mode
# --crop_mode normal/fit/fill
crop_mode="normal"

# Crop offset
# Only affects normal mode.
# --crop_offset northwest/north/northeast/west/center
#               east/southwest/south/southeast
crop_offset="center"

# Image size
# The image is half the terminal width by default.
# --size auto, 00px, 00%
image_size="auto"

# Right gap between image and text
# --gap num
gap=2

# Image offsets
# --xoffset px
# --yoffset px
yoffset=0
xoffset=0


# }}}

# Ascii Options {{{


# Default ascii image to use
# When this is set to distro it will use your
# distro's logo as the ascii.
# --ascii 'distro', path/to/ascii
ascii="distro"

# Ascii colors
# When this is set to distro it will use your
# ditro's colors to color the ascii.
# NOTE: You can also set this to a range of colors
# which will allow you to custom color distro logos
# --ascii_colors distro
# --ascii_colors 2 4 5 6
ascii_colors=(distro)

# Logo size
# Arch, Crux and Gentoo have a smaller logo
# variant. Changing the value below to 'small'
# will make neofetch use the small logo.
# --ascii_logo_size small, normal
ascii_logo_size="normal"


# }}}

# Scrot Options {{{


# Whether or not to always take a screenshot
# You can manually take a screenshot with "--scrot" or "-s"
scrot="off"

# Screenshot program to launch
# --scrot_cmd
scrot_cmd="scrot -c -d 3"

# Scrot dir
# Where to save the screenshots
# --scrot_dir /path/to/screenshot/folder
scrot_dir="$HOME/Pictures/"

# Scrot filename
# What to name the screenshots
# --scrot_name str
scrot_name="neofetch-$(date +%F-%T).png"


# }}}

# Stdout options {{{

# Separator for stdout mode
# --stdout_separator string
stdout_separator="  "

# }}}

# Config Options {{{


# Enable/Disable config file
# --config off, none
config="on"

# Path to custom config file location
# --config path/to/config
config_file="${XDG_CONFIG_HOME:-${HOME}/.config}/neofetch/config"


# }}}


# }}}


# Detect OS {{{

case "$(uname)" in
    "Linux")   os="Linux" ;;
    "Darwin")  os="Mac OS X" ;;
    "OpenBSD") os="OpenBSD" ;;
    *"BSD")    os="BSD" ;;
    "CYGWIN"*) os="Windows" ;;
    *) printf "%s\n" "Unknown OS detected: $(uname)"; exit 1 ;;
esac

# }}}


# Images {{{


# Wallpaper {{{

getwallpaper () {
    case "$os" in
        "Linux" | *"BSD")
            if type -p feh >/dev/null 2>&1 && [ -f "$HOME/.fehbg" ]; then
                img="$(awk -F\' '/feh/ {printf $2}' "$HOME/.fehbg")"

            elif type -p nitrogen >/dev/null 2>&1; then
                img="$(awk -F'=' '/file/ {printf $2;exit;}' "$XDG_CONFIG_HOME/nitrogen/bg-saved.cfg")"

            elif type -p gsettings >/dev/null 2>&1; then
                # Get DE if user has disabled the function.
                [ -z "$de" ] && getde

                case "$de" in
                    "MATE"*) img="$(gsettings get org.mate.background picture-filename 2>/dev/null)" ;;
                    *) img="$(gsettings get org.gnome.desktop.background picture-uri 2>/dev/null)" ;;
                esac

                # Strip quotes etc from the path.
                img=${img/'file://'}
                img=${img//\'}
            fi
        ;;

        "Mac OS X")
            img="$(osascript -e 'tell application "System Events" to picture of current desktop')"
        ;;

        "Windows")
            case "$distro" in
                "Windows XP")
                    img="/cygdrive/c/Documents and Settings/${USER}"
                    img+="/Local Settings/Application Data/Microsoft"
                    img+="/Wallpaper1.bmp"
                ;;

                "Windows"*)
                    img="$APPDATA/Microsoft/Windows/Themes"
                    img+="/TranscodedWallpaper.jpg"
                ;;
            esac
        ;;
    esac

    # If img is an xml file don't use it.
    [ "${img/*\./}" == "xml" ] && img=""
}

# }}}

# Ascii {{{

getascii () {
    if [ ! -f "$ascii" ] || [ "$ascii" == "distro" ]; then
        # Lowercase the distro name
        if [ "$version" -le 3 ]; then
            ascii=$(tr '[:upper:]' '[:lower:]' <<< "$ascii_distro")
        else
            ascii=${ascii_distro,,}
        fi

        [ "$ascii_logo_size" == "small" ] && \
            ascii="${ascii/ *}_small"

        if [ -f "/usr/share/neofetch/ascii/distro/${ascii/ *}" ]; then
            ascii="/usr/share/neofetch/ascii/distro/${ascii/ *}"

        elif [ -f "/usr/local/share/neofetch/ascii/distro/${ascii/ *}" ]; then
            ascii="/usr/local/share/neofetch/ascii/distro/${ascii/ *}"

        else
            getscriptdir

            # If the ascii file doesn't exist fallback to text mode.
            if [ ! -f "$script_dir/ascii/distro/${ascii/ *}" ]; then
                padding="\033[0C"
                image="off"
                return
            fi

            ascii="$script_dir/ascii/distro/${ascii/ *}"
        fi

        # We only use eval in the distro ascii files.
        print="$(eval printf "$(<"$ascii")")"
    else
        case "${ascii_colors[0]}" in
            "distro") ascii_color="$c1" ;;
            *) ascii_color="\033[38;5;${ascii_colors[0]}m" ;;
        esac

        print="${ascii_color}$(<"$ascii")"
    fi

    # Set locale to get correct padding
    export LC_ALL="$SYS_LOCALE"

    # Turn the file into a variable and strip escape codes.
    ascii_strip=$(<"$ascii")
    ascii_strip=${ascii_strip//\$\{??\}}
    ascii_strip=${ascii_strip//\\}

    # Get length of longest line
    ascii_size=($(awk 'END {print NR}length>max{max=length}END{print max}' <<< "$ascii_strip"))
    lines=$((ascii_size[0] + 1))
    ascii_length=${ascii_size[1]}

    padding="\033[$((ascii_length + gap))C"
    printf "%b%s" "$print"

    export LC_ALL=C
}


# }}}

# Image {{{

getimage () {
    # Fallback to ascii mode if imagemagick isn't installed.
    type -p convert >/dev/null 2>&1 || image="ascii"

    # Get terminal lines
    lines=$(tput lines)

    case "$image" in
        "wall") getwallpaper ;;
        "ascii") getascii; return ;;
        *)
            if [ "${image: -1}" == "/" ]; then
                files=("$image"*.png "$image"*.jpg)
                img="$(printf "%s" "${files[RANDOM % ${#files[@]}]}")"
            else
                img="$image"
            fi
        ;;
    esac

    # Get terminal width and height
    stty -echo
    if [ -n "$TMUX" ]; then
        printf "%b%s" "\033Ptmux;\033\033[14t\033\033[c\033\\"
    else
        printf "%b%s" "\033[14t\033[c"
    fi

    # The ascape code above prints the output AFTER the prompt so this
    # loop below reads it as input. wtf xterm
    read -d c -s -r term_size; stty echo

    # Split the string
    term_size=${term_size//'['}
    term_size=${term_size/';'}
    term_size=${term_size/$'\E4'}
    term_size=${term_size/t*}
    term_height=${term_size/';'*}
    term_width=${term_size/*';'}


    # If $img isn't a file or the terminal doesn't support xterm escape sequences,
    # fallback to ascii mode.
    if [ ! -f "$img" ] || [ ${#term_size} -le 5 ]; then
        image="ascii"
        getascii
        return
    fi

    # Get terminal columns
    columns=$(tput cols)

    # Calculate font size
    font_width=$((term_width / columns))
    font_height=$((term_height / lines))

    # Image size is half of the terminal
    case "$image_size" in
        "auto")
            image_size=$((columns * font_width / 2))
            term_height=$((term_height - term_height / 4))

            [ "$term_height" -lt "$image_size" ] && \
                image_size="$term_height"
        ;;

        *"%")
            percent=${image_size/\%}
            image_size=$((percent * term_width / 100))

            [ "$((percent * term_height / 50))" -lt "$image_size" ] && \
                image_size=$((percent * term_height / 100))
        ;;
    esac
    image_size=${image_size/px}

    # Where to draw the image
    case "$image_position" in
        "left")
            # Padding is half the terminal width + gap
            padding="\033[$((image_size / font_width + gap + xoffset/font_width))C"
        ;;

        "right")
            padding="\033[0C"
            xoffset=$((columns * font_width / 2 - gap))
        ;;
    esac

    # Make the directory if it doesn't exist
    mkdir -p "$thumbnail_dir"

    # Check to see if the image has a file extension, if it doesn't
    # then add one.
    case "${img##*/}" in
        *"."*) imgname="$crop_mode-$crop_offset-$image_size-${img##*/}" ;;
        *) imgname="$crop_mode-$crop_offset-$image_size-${img##*/}.jpg" ;;
    esac

    # Check to see if the thumbnail exists before we do any cropping.
    if [ ! -f "$thumbnail_dir/$imgname" ]; then
        # Get image size so that we can do a better crop
        size=$(identify -format "%w %h" "$img")
        width=${size%% *}
        height=${size##* }

        # This checks to see if height is geater than width
        # so we can do a better crop of portrait images.
        size=$height
        [ "$height" -gt "$width" ] && size=$width

        case "$crop_mode" in
            fit)
                c=$(convert "$img" \
                    -colorspace srgb \
                    -format "%[pixel:p{0,0}]" info:)

                convert \
                    "$img" \
                    -trim +repage \
                    -gravity south \
                    -background "$c" \
                    -extent "$size"x"$size" \
                    -scale "$image_size"x"$image_size" \
                    "$thumbnail_dir/$imgname"
            ;;

            fill)
                convert \
                    "$img" \
                    -trim +repage \
                    -scale "$image_size"x"$image_size"^ \
                    -extent "$image_size"x"$image_size" \
                    "$thumbnail_dir/$imgname"
            ;;

            *)
                convert \
                    "$img" \
                    -gravity $crop_offset \
                    -crop "$size"x"$size"+0+0 \
                    -quality 95 \
                    -scale "$image_size"x"$image_size" \
                    "$thumbnail_dir/$imgname"
            ;;
        esac
    fi

    # The final image
    img="$thumbnail_dir/$imgname"
}

takescrot () {
    $scrot_cmd "${scrot_dir}${scrot_name}"
}

# }}}

# Find w3m-img {{{

# Find w3mimgdisplay automatically
getw3m_img_path () {
    if [ -x "$w3m_img_path" ]; then
        return

    elif [ -x "/usr/lib/w3m/w3mimgdisplay" ]; then
        w3m_img_path="/usr/lib/w3m/w3mimgdisplay"

    elif [ -x "/usr/libexec/w3m/w3mimgdisplay" ]; then
        w3m_img_path="/usr/libexec/w3m/w3mimgdisplay"

    elif [ -x "/usr/lib64/w3m/w3mimgdisplay" ]; then
        w3m_img_path="/usr/lib64/w3m/w3mimgdisplay"

    elif [ -x  "/usr/libexec64/w3m/w3mimgdisplay" ]; then
        w3m_img_path="/usr/libexec64/w3m/w3mimgdisplay"

    else
        image="ascii"
    fi
}

# }}}


# }}}


# Text Formatting {{{


# Info {{{

info () {
    # $1 is the subtitle
    subtitle="$1"

    # Call the function and update variable
    if [ -z "$2" ]; then
        "get$1" 2>/dev/null
        eval output="\$${1}"

    else
        "get$2" 2>/dev/null
        eval output="\$${2}"
    fi

    # If the output is empty, don't print anything
    [ -z "$output" ] && return

    case "$1" in
        title)
            string="${bold}${title_color}${output}"
            string="${string/@/${at_color}@${title_color}}"
            length=${#output}
        ;;

        underline)
            string="${underline_color}${output}"
        ;;

        *)
            string="${bold}${subtitle_color}${subtitle}${clear}"
            string+="${colon_color}: ${info_color}${output}"
            length=$((${#subtitle} +  ${#output} + 2))
        ;;
    esac

    # If there's no subtitle don't print one
    [ -z "$2" ] && string=${string/*: }

    # Print the string
    printf "%b%s\n" "${padding}${string}${clear}"
}

# }}}

# Prin {{{

prin () {
    if [ -z "$2" ]; then
        string="${info_color}${1}"
        length=${#1}

    else
        string="${bold}${subtitle_color}${1}${clear}"
        string+="${colon_color}: ${info_color}${2}"
        length=$((${#subtitle} +  ${#2} + 1))
    fi

    # Print the info
    printf "%b%s\n" "${padding}${string}${clear}"
}

# }}}

# Stdout {{{

stdout () {
    # Read args early for the separator
    stdout_separator_flag="$(awk -F '--stdout_separator ' '{printf $2}' <<< "${args[@]}")"
    stdout_separator_flag=${stdout_separator_flag/ '--'*}

    [ ! -z "$stdout_separator_flag" ] && \
        stdout_separator="$stdout_separator_flag"

    for func in "${args[@]}"; do
        case "$func" in
            "--"*) break ;;
            *)
                "get$func" 2>/dev/null
                eval output="\$$func"
                stdout+="${output}${stdout_separator}"
            ;;
        esac
    done

    printf "%s" "${stdout%%${stdout_separator}}"
    exit
}

# }}}

# Underline {{{

getunderline () {
    case "$underline_enabled" in
        "on")
            underline=$(printf %"$length"s)
            underline=${underline// /$underline_char}
         ;;
        "off") underline="" ;;
    esac
}

# }}}

# Colors {{{

colors () {
    # Change color of logo based on distro
    case "$ascii_distro" in
        "Arch"* | "Antergos"*)
            setcolors 6 4
        ;;

        "CentOS"*)
            setcolors 3 2 4 5 7
        ;;

        "CRUX"* | "Chakra"* | "gNewSense"* | "SailfishOS"* | "Alpine"* | "Ubuntu-GNOME"* | "Qubes"*)
            setcolors 4 5 7
        ;;

        "Chrom"*)
            setcolors 2 1 3 4 7
            ascii_distro="chrome"
        ;;

        "Debian"* | "FreeBSD"* | "Elementary"* | "CrunchBang"* | "Ubuntu"*)
            setcolors 7 1 3
        ;;

        "Red"*)
            setcolors 7 1 3
            ascii_distro="redhat"
        ;;

        "Fedora"* | "Sabayon"* | "Frugalware"* | "Exherbo"*)
            setcolors 7 4 1
        ;;

        "Gentoo"* | "Funtoo"* | "SteamOS"*)
            setcolors 7 5
        ;;

        "Kali"*)
            setcolors 4 8
        ;;

        *"OS X"* )
            setcolors 2 3 1 1 5 4
            ascii_distro="mac"
        ;;

        "OpenMandriva"*)
            setcolors 4 3
        ;;

        "Mageia"*)
            setcolors 7 6
        ;;

        "Peppermint"*)
            setcolors 7 1
        ;;

        *"Mint"*)
            setcolors 7 2
            ascii_distro="mint"
        ;;

        "LMDE"* | "Chapeau"*)
            setcolors 7 2
        ;;

        "NetBSD"* | "Parabola"* | "Tails"* | "BLAG"*)
            setcolors 5 7
        ;;

        "OpenBSD"*)
            setcolors 3 3 6 1 8
        ;;

        "OpenSuse"* | "Manjaro"* | "Deepin"*)
            setcolors 2 7
        ;;

        "PCLinuxOS"* | "Slackware"* | "KaOS"* | "Kubuntu"* | "Lubuntu"* | "Xubuntu"*)
            setcolors 4 7 1
        ;;

        "Puppy"* | "Quirky Werewolf"* | "Precise Puppy"*)
            setcolors 4
            ascii_distro="puppy"
        ;;

        "Scientific"*)
            setcolors 4 1 7
        ;;

        "Solus"*)
            setcolors 7 8
        ;;

        "Trisquel"* | "NixOS"* | "Zorin"*)
            setcolors 4 6
        ;;

        "Travis")
            setcolors 3 1 0 7 4
        ;;

        "void"*)
            setcolors 2 8
        ;;

        "Windows 10"*)
            setcolors 6
            ascii_distro="windows10"
        ;;

        "Windows"*)
            setcolors 1 2 4 3
        ;;

        "Raspbian"* | *)
            setcolors 2 1
        ;;
    esac

    # Overwrite distro colors if '$ascii_colors' doesn't
    # equal 'distro'.
    [ "${ascii_colors[0]}" != "distro" ] && \
        setcolors ${ascii_colors[@]}
}

setcolors () {
    c1="$(color $1)"
    c2="$(color $2)"
    c3="$(color $3)"
    c4="$(color $4)"
    c5="$(color $5)"
    c6="$(color $6)"

    if [ "${colors[0]}" == "distro" ]; then
        title_color="$c1"
        at_color="\033[0m"
        underline_color="\033[0m"
        subtitle_color="$c2"
        colon_color="\033[0m"
        info_color="\033[0m"

        # If the second color is white use the first for the subtitle
        [ "$2" == 7 ] && subtitle_color="\033[0m\033[3${1}m"
    else
        title_color="$(color ${colors[0]})"
        at_color="$(color ${colors[1]})"
        underline_color="$(color ${colors[2]})"
        subtitle_color="$(color ${colors[3]})"
        colon_color="$(color ${colors[4]})"
        info_color="$(color ${colors[5]})"
    fi

    if [ "$progress_color_elapsed" == "distro" ]; then
        progress_color_elapsed="$(color 7)"
    else
        progress_color_elapsed="$(color $progress_color_elapsed)"
    fi

    case "$progress_color_total $1" in
        distro\ [736]) progress_color_total="$c2" ;;
        distro\ [0-9]) progress_color_total="$c1" ;;
        *) progress_color_total="$(color $progress_color_total)" ;;
    esac
}

color () {
    if [ "$1" == 7 ]; then
        printf "%b%s" "\033[0m"
    else
        printf "%b%s" "\033[0m\033[3${1}m"
    fi
}


# }}}

# Bold {{{

bold () {
    case "$bold" in
        "on") bold="\033[1m" ;;
        "off") bold="" ;;
    esac
}

# }}}

# Linebreak {{{

getlinebreak () {
   linebreak=" "
}

# }}}

clear="\033[0m"


# }}}


# Other {{{


# Get script directory {{{

getscriptdir () {
    # Use $0 to get the script's physical path.
    cd "${0%/*}" || exit
    script_dir=${0##*/}

    # Iterate down a (possible) chain of symlinks.
    while [ -L "$script_dir" ]; do
        script_dir="$(readlink "$script_dir")"
        cd "${script_dir%/*}" || exit
        script_dir="${script_dir##*/}"
    done

    # Final directory
    script_dir="$(pwd -P)"
}

# }}}

# Source Config {{{

# Check for $config_file first
getconfig () {
    # Check $config_file
    if [ -f "$config_file" ]; then
        source "$config_file"
        return
    fi
    mkdir -p "$XDG_CONFIG_HOME/neofetch/"

    # Check $XDG_CONFIG_HOME/neofetch and create the
    # dir/files if they don't exist.
    if [ -f "$XDG_CONFIG_HOME/neofetch/config" ]; then
        source "$XDG_CONFIG_HOME/neofetch/config"

    elif [ -f "/usr/share/neofetch/config" ]; then
        cp "/usr/share/neofetch/config" "$XDG_CONFIG_HOME/neofetch"
        source "$XDG_CONFIG_HOME/neofetch/config"

    elif [ -f "/usr/local/share/neofetch/config" ]; then
        cp "/usr/local/share/neofetch/config" "$XDG_CONFIG_HOME/neofetch"
        source "$XDG_CONFIG_HOME/neofetch/config"

    else
        getscriptdir

        cp "$script_dir/config/config" "$XDG_CONFIG_HOME/neofetch"
        source "$XDG_CONFIG_HOME/neofetch/config"
    fi
}

# Check the commandline flags early for '--config none/off'
case "$@" in
    *"--config off"* | *'--config "off"'* | *"--config 'off'"* | \
    *"--config none"* | *'--config "none"'* | *"--config 'none'"* | *"--stdout"*)
        config="off"
    ;;
esac
[ "$config" == "on" ] && getconfig

# }}}

# Progress Bars {{{

bar() {
    # Get the values
    elapsed=$(($1 * progress_length / $2))

    # Create the bar with spaces
    prog=$(printf %"$elapsed"s)
    total=$(printf %"$((progress_length - elapsed))"s)

    # Set the colors and swap the spaces for $progress_char
    bar="${progress_color_elapsed}${prog// /$progress_char}"
    bar+="${progress_color_total}${total// /$progress_char}"
    printf "%b%s\n" "${bar}${clear}"
}

# }}}

# Cache {{{

cache () {
    mkdir -p "$3/neofetch"
    echo "${1/*-}=\"$2\"" > "$3/neofetch/${1/*-}"
}

# }}}

# KDE Config directory {{{

kdeconfigdir () {
    if [ -n "$KDE_CONFIG_DIR" ]; then
        kde_config_dir="$KDE_CONFIG_DIR"

    elif type -p kde5-config >/dev/null 2>&1; then
        kde_config_dir=$(kde5-config --localprefix)

    elif type -p kde4-config >/dev/null 2>&1; then
        kde_config_dir=$(kde4-config --localprefix)

    elif type -p kde-config >/dev/null 2>&1; then
        kde_config_dir=$(kde-config --localprefix)
    fi
}

# }}}


# }}}


# Usage {{{


usage () { cat << EOF

    usage: neofetch --option "value" --option "value"

    NOTE: There's also a config option for each flag below.

    Info:
    --disable infoname          Allows you to disable an info line from appearing
                                in the output.
                                NOTE: You can supply multiple args. eg.
                                'neofetch --disable cpu gpu disk shell'
    --osx_buildversion on/off   Hide/Show Mac OS X build version.
    --osx_codename on/off       Hide/Show Mac OS X codename.
    --os_arch on/off            Hide/Show Windows architecture.
    --speed_type type           Change the type of cpu speed to display.
                                Possible values: current, min, max, bios,
                                scaling_current, scaling_min, scaling_max
                                NOTE: This only support Linux with cpufreq.
    --cpu_shorthand type        Shorten the output of CPU
                                Possible values: name, speed, tiny, on, off
    --cpu_cores on/off          Whether or not to display the number of CPU cores
    --kernel_shorthand on/off   Shorten the output of kernel
    --uptime_shorthand on/off   Shorten the output of uptime (tiny, on, off)
    --refresh_rate on/off       Whether to display the refresh rate of each monitor
                                Unsupported on Windows
    --gpu_shorthand on/off      Shorten the output of GPU (tiny, on, off)
    --gtk_shorthand on/off      Shorten output of gtk theme/icons
    --gtk2 on/off               Enable/Disable gtk2 theme/icons output
    --gtk3 on/off               Enable/Disable gtk3 theme/icons output
    --shell_path on/off         Enable/Disable showing \$SHELL path
    --shell_version on/off      Enable/Disable showing \$SHELL version
    --battery_num num           Which battery to display, default value is 'all'
    --battery_shorthand on/off  Whether or not each battery gets its own line/title
    --ip_host url               Url to ping for public IP
    --song_shorthand on/off     Print the Artist/Title on seperate lines
    --birthday_shorthand on/off Shorten the output of birthday
    --birthday_time on/off      Enable/Disable showing the time in birthday output
    --birthday_format format    Format the birthday output. (Uses 'date' cmd format)


    Text Formatting:
    --colors x x x x x x        Changes the text colors in this order:
                                title, @, underline, subtitle, colon, info
    --underline_char char       Character to use when underlining title
    --line_wrap on/off          Enable/Disable line wrapping
    --bold on/off               Enable/Disable bold text
    --prompt_height num         Set this to your prompt height to fix issues with
                                the text going off screen at the top


    Color Blocks:
    --color_blocks on/off       Enable/Disable the color blocks
    --block_width num           Width of color blocks
    --block_range start end     Range of colors to print as blocks


    Progress Bars:
    --progress_char char        Character to use when drawing progress bars.
    --progress_length num       Length in spaces to make the progress bars.
    --progress_colors num num   Colors to make the progress bar.
                                Set in this order: elapsed, total
    --cpu_display mode1 mode2   Which shorthand to use and how CPU usage should be printed
                                mode1 takes: name, speed, tiny, on, off
                                mode2 takes: info, bar, infobar, barinfo
    --memory_display mode       Which way should the memory progress bar be added
                                Takes bar, infobar, barinfo
    --battery_display mode      Which way should the battery progress bar be added
                                Takes bar, infobar, barinfo
    --disk_display mode         Which way should the disk progress bar be added
                                Takes bar, infobar, barinfo, perc


    Image:
    --image type                Image source. Where and what image we display.
                                Possible values: wall, ascii,
                                /path/to/img, /path/to/dir/, off
    --size 20px | --size 20%    Size to make the image, takes pixels or a percentage.
    --image_position left/right Where to display the image: (Left/Right)
    --crop_mode mode            Which crop mode to use
                                Takes the values: normal, fit, fill
    --crop_offset value         Change the crop offset for normal mode.
                                Possible values: northwest, north, northeast,
                                west, center, east, southwest, south, southeast

    --xoffset px                How close the image will be to the left edge of the
                                window. This only works with w3m.
    --yoffset px                How close the image will be to the top edge of the
                                window. This only works with w3m.
    --gap num                   Gap between image and text.
                                NOTE: --gap can take a negative value which will
                                move the text closer to the left side.
    --clean                     Remove all cropped images


    Ascii:
    --ascii value               Where to get the ascii from, Possible values:
                                distro, /path/to/ascii
    --ascii_colors x x x x x x  Colors to print the ascii art
    --ascii_distro distro       Which Distro's ascii art to print


    Stdout:
    --stdout info info          Launch neofetch in stdout mode which prints the info
                                in a plain-text format that you can use with
                                lemonbar etc.
    --stdout_separator string   String to use as a separator in stdout mode.


    Screenshot:
    --scrot /path/to/img        Take a screenshot, if path is left empty the screen-
                                shot function will use \$scrot_dir and \$scrot_name.
    --scrot_cmd cmd             Screenshot program to launch


    Other:
    --config /path/to/config    Specify a path to a custom config file
    --config none               Launch the script without a config file
    --help                      Print this text and exit

EOF
exit 1
}


# }}}


# Args {{{


while [ "$1" ]; do
    case $1 in
        # Info
        --os_arch) os_arch="$2" ;;
        --osx_buildversion) osx_buildversion="$2" ;;
        --osx_codename) osx_codename="$2" ;;
        --cpu_cores) cpu_cores="$2" ;;
        --speed_type) speed_type="$2" ;;
        --kernel_shorthand) kernel_shorthand="$2" ;;
        --uptime_shorthand) uptime_shorthand="$2" ;;
        --cpu_shorthand) cpu_shorthand="$2" ;;
        --gpu_shorthand) gpu_shorthand="$2" ;;
        --refresh_rate) refresh_rate="$2" ;;
        --gtk_shorthand) gtk_shorthand="$2" ;;
        --gtk2) gtk2="$2" ;;
        --gtk3) gtk3="$2" ;;
        --shell_path) shell_path="$2" ;;
        --shell_version) shell_version="$2" ;;
        --battery_num) battery_num="$2" ;;
        --battery_shorthand) battery_shorthand="$2" ;;
        --ip_host) public_ip_host="$2" ;;
        --song_shorthand) song_shorthand="$2" ;;
        --birthday_shorthand) birthday_shorthand="$2" ;;
        --birthday_time) birthday_time="$2" ;;
        --birthday_format) birthday_format="$2" ;;
        --disable)
            for func in "$@"; do
                case "$func" in
                    "--disable") continue ;;
                    "--"*) return ;;
                    *) unset -f "get$func" ;;
                esac
            done
        ;;

        # Text Colors
        --colors)
            unset colors
            for arg in "$2" "$3" "$4" "$5" "$6" "$7"; do
                case "$arg" in
                    "--"*) break ;;
                    *) colors+=($arg)
                esac
            done
            colors+=(7 7 7 7 7 7)
        ;;

        # Text Formatting
        --underline) underline="$2" ;;
        --underline_char) underline_char="$2" ;;
        --line_wrap) line_wrap="$2" ;;
        --bold) bold="$2" ;;
        --prompt_height) prompt_height="$2" ;;

        # Color Blocks
        --color_blocks) color_blocks="$2" ;;
        --block_range) start=$2; end=$3 ;;
        --block_width) block_width="$2" ;;

        # Progress Bars
        --progress_char) progress_char="$2" ;;
        --progress_length) progress_length="$2" ;;
        --progress_colors)
            progress_color_elapsed="$2"
            progress_color_total="$3"
        ;;
        --cpu_display)
            cpu_shorthand="$2"
            cpu_display="$3"
        ;;
        --memory_display) memory_display="$2" ;;
        --battery_display) battery_display="$2" ;;
        --disk_display) disk_display="$2" ;;

        # Image
        --image)
            image="$2"
            case "$2" in "--"* | "") image="ascii" ;; esac
        ;;

        --size) image_size="$2" ;;
        --image_position) image_position="$2" ;;
        --crop_mode) crop_mode="$2" ;;
        --crop_offset) crop_offset="$2" ;;
        --xoffset) xoffset="$2" ;;
        --yoffset) yoffset="$2" ;;
        --gap) gap="$2" ;;
        --clean)
            rm -rf "$thumbnail_dir"
            rm -rf "/Library/Caches/neofetch/"
            exit
        ;;

        # Ascii
        --ascii)
            image="ascii"
            ascii="$2"
            case "$2" in "--"* | "") ascii="distro" ;; esac
        ;;

        --ascii_colors)
            unset ascii_colors
            for arg in "$2" "$3" "$4" "$5" "$6" "$7"; do
                case "$arg" in
                    "--"*) break ;;
                    *) ascii_colors+=($arg)
                esac
            done
            ascii_colors+=(7 7 7 7 7 7)
        ;;

        --ascii_distro)
            ascii_distro="$2"
            case "$2" in "--"* | "") ascii_distro="$distro" ;; esac
        ;;

        --ascii_logo_size) ascii_logo_size="$2" ;;

        # Screenshot
        --scrot | -s)
            scrot="on"
            if [ "$2" ]; then
                scrot_name="${2##*/}"
                scrot_dir="${2/$scrot_name}"
            fi
        ;;
        --scrot_cmd) scrot_cmd="$2" ;;

        # Stdout
        --stdout)
            unset info_color prin clear bar
            stdout_mode="on"
            config="off"
            case "$2" in
                "--"* | "") printf "%s\n" "--stdout requires at least one argument"; exit ;;
                *) shift; args=("$@"); stdout ;;
            esac
        ;;

        # Other
        --config)
            case "$2" in
                "none" | "off") config="off" ;;
                *) config_file="$2"; config="on"; getconfig ;;
            esac
        ;;
        --test)
            info=(title underline distro kernel uptime packages shell resolution de wm wmtheme theme icons cpu gpu memory font disk battery song localip publicip users birthday)

            refresh_rate="on"
            shell_version="on"
            cpu_display="infobar"
            memory_display="infobar"
            disk_display="infobar"

            printinfo () {
                if [ ! -z "$TRAVIS_OS_NAME" ]; then
                    info linebreak
                    info linebreak
                fi

                for func in "${info[@]}"; do
                    info "$(tr '[:lower:]' '[:upper:]' <<< "$func")" $func
                done

                info linebreak
                info cols
                info linebreak
                printf "%b%s" "\033[$(tput lines)H"
            }
        ;;

        --help) usage ;;
    esac

    shift
done


# }}}


# Call Functions and Finish Up {{{


# Restore cursor and clear screen on ctrl+c
trap 'printf "\033[?25h"; clear; exit' 2

getdistro
colors
bold

if [ "$image" != "off" ]; then
    # If the script exits for any reason, unhide the cursor.
    trap 'printf "\033[?25h"' EXIT

    # Clear the scren
    clear

    # Hide the cursor
    printf "\033[?25l"

    # If iterm2 is detected use iterm2 backend.
    if [ -n "$ITERM_PROFILE" ]; then
        image_backend="iterm2"
    else
        image_backend="w3m"
    fi

    # Find w3mimgdisplay
    [ "$image_backend" == "w3m" ] && \
    [ "$image" != "ascii" ] && \
        getw3m_img_path

    # Get the image
    getimage
fi

# Display the image if enabled
if [ "$image" != "off" ] && [ "$image" != "ascii" ]; then
    case "$image_backend" in
        "w3m")
            printf "%b%s\n" "0;1;$xoffset;$yoffset;$image_size;$image_size;;;;;$img\n4;\n3;" |\
            $w3m_img_path 2>/dev/null || padding="\033[0C"
        ;;

        "iterm2")
            printf "%b%s\a\n" "\033]1337;File=width=${image_size}px;height=${image_size}px;inline=1:$(base64 < "$img")"
        ;;
    esac
fi

# Disable line wrap
[ "$line_wrap" == "off" ] && printf "\033[?7l"

# Move cursor to the top
[ "$image" != "off" ] && printf "\033[0H"

# Print the info
printinfo

if [ "$image" != "off" ]; then
    # Get cursor position
    info_height="$(stty -echo; IFS=';' read -rdR -t 1 -d c -p $'\033[6n\033[c' ROW COL; printf "%s" "${ROW#*[}"; stty echo)"

    # Set cursor position dynamically based on height of ascii/text.
    [ "${lines:-0}" -lt "${info_height:-0}" ] && lines="$info_height"

    printf "%b%s" "\033[${lines}H\033[${prompt_height}A"
fi

# Re-enable line wrap
[ "$line_wrap" == "off" ] && printf "%b%s" "\033[?7h"

# If enabled take a screenshot
if [ "$scrot" == "on" ]; then
    takescrot
fi

# }}}
