# This file is automatically generated. Please do not modify.

from . import AsciiArt

amogos = AsciiArt(match=r'''"AmogOS"*''', color='15 6', ascii=r"""
${c1}             ___________
            /           \
           /   ${c2}______${c1}    \
          /   ${c2}/      \${c1}    \
          |  ${c2}(        )${c1}    \
         /    ${c2}\______/${c1}     |
         |                 |
        /                   \
        |                   |
        |                   |
       /                    |
       |                    |
       |     _______        |
  ____/     /       \       |
 /          |       |       |
 |          /   ____/       |
 \_________/   /            |
               \         __/
                \_______/
""")
    