# This file is automatically generated. Please do not modify.

from . import AsciiArt

aoscosretro_small = AsciiArt(match=r'''"aoscosretro_small"''', color='4 7 1 3', ascii=r"""
${c2}    _____   ${c1}_____${c2}
  -'     '-${c1}|     |${c2}
 /     ___ ${c1}|     |${c2}
|     / _ \${c1}|_____|${c2}
'    / /_\ \
 \  / _____ \${c4}___
  ${c3}|${c2}/_/  ${c3}|   ${c4}|   |
  ${c3}|     |   ${c4}|___|
  ${c3}|_____|
""")
    