# This file is automatically generated. Please do not modify.

from . import AsciiArt

bonsai = AsciiArt(match=r'''"bonsai"*''', color='6 2 3', ascii=r"""
${c2}   ,####,
   ${c2}#######,  ${c2},#####,
   ${c2}#####',#  ${c2}'######
    ${c2}''###'${c3}';,,,'${c2}###'
   ${c3}       ,;  ''''
   ${c3}      ;;;   ${c2},#####,
   ${c3}     ;;;'  ,,;${c2};;###
   ${c3}     ';;;;''${c2}'####'
   ${c3}      ;;;
   ${c3}   ,.;;';'',,,
   ${c3}  '     '
${c1} #
 #                        O
 ##, ,##,',##, ,##  ,#,   ,
 # # #  # #''# #,,  # #   #
 '#' '##' #  #  ,,# '##;, #
""")
    