# This file is automatically generated. Please do not modify.

from . import AsciiArt

centos_small = AsciiArt(match=r'''"centos_small"*''', color='3 2 4 5 7', ascii=r"""
${c2} ____${c1}^${c4}____
${c2} |\  ${c1}|${c4}  /|
${c2} | \ ${c1}|${c4} / |
${c4}<---- ${c3}---->
${c3} | / ${c2}|${c1} \ |
${c3} |/__${c2}|${c1}__\|
${c2}     v
""")
    