# This file is automatically generated. Please do not modify.

from . import AsciiArt

droidian = AsciiArt(match=r'''"Droidian"*''', color='2 10', ascii=r"""
${c2}       _,met$$$$$gg.
   ,g$$$$$$$$$$$$$$$$P.
 ,$$P'              `$$$.
',$$P       ,ggs.     `$$b:
`d$$'     ,$P"'   ${c1}.${c2}    $$$
 $$P      d$'     ${c1},${c2}    $$P
 $$:      $$.   ${c1}-${c2}    ,d$$'
 $$;      Y$b._   _,d$P'
 Y$$.    ${c1}`.${c2}`"Y$$$$P"'
${c2} `$$b      ${c1}"-.__
${c2}  `Y$$
  `Y$$.
     `$$b.
       `Y$$b.
          `"Y$b._
""")
    