# This file is automatically generated. Please do not modify.

from . import AsciiArt

encryptos = AsciiArt(match=r'''"EncryptOS"*''', color='2 5 6', ascii=r"""
${c2}                  *******
${c2}                ***       **.
${c2}                **         **
${c2}                **         **

${c2}              *****************
${c2}             ,,,,,,,,,,,,,,,,***
${c2}             ,,,,,,,     ,,,,,,,
${c2}             ,,,,,,,     ,,,,,,,
${c2}             ,,,,,,,     ,,,,,,,
${c2}             ,,,,,,,     ,,,,,,,
${c2}             ,,,,,,,,,,,,,,,,,,,
${c2}                 ,,,,,,,,,,,,.
""")
    