# This file is automatically generated. Please do not modify.

from . import AsciiArt

freemint = AsciiArt(match=r'''"FreeMiNT"*''', color='7', ascii=r"""
${c1}          ##
          ##         #########
                    ####      ##
            ####  ####        ##
####        ####  ##        ##
        ####    ####      ##  ##
        ####  ####  ##  ##  ##
            ####  ######
        ######  ##  ##  ####
      ####    ################
    ####        ##  ####
    ##            ####  ######
    ##      ##    ####  ####
    ##    ##  ##    ##  ##  ####
      ####  ##          ##  ##
""")
    