# This file is automatically generated. Please do not modify.

from . import AsciiArt

glaucus = AsciiArt(match=r'''"glaucus"*''', color='5', ascii=r"""
${c1}             ,,        ,d88P
           ,d8P    ,ad8888*
         ,888P    d88888*     ,,ad8888P*
    d   d888P   a88888P*  ,ad8888888*
  .d8  d8888:  d888888* ,d888888P*
 .888; 88888b d8888888b8888888P
 d8888J888888a88888888888888P*    ,d
 88888888888888888888888888P   ,,d8*
 888888888888888888888888888888888*
 *8888888888888888888888888888888*
  Y888888888P* `*``*888888888888*
   *^888^*            *Y888P**
""")
    