# This file is automatically generated. Please do not modify.

from . import AsciiArt

gobolinux = AsciiArt(match=r'''"GoboLinux"*''', color='5 4 6 2', ascii=r"""
${c1}  _____       _
 / ____|     | |
| |  __  ___ | |__   ___
| | |_ |/ _ \| '_ \ / _ \
| |__| | (_) | |_) | (_) |
 \_____|\___/|_.__/ \___/
""")
    