# This file is automatically generated. Please do not modify.

from . import AsciiArt

guix = AsciiArt(match=r'''"Guix"*''', color='3 7 6 1 8', ascii=r"""
${c1} ..                             `.
 `--..```..`           `..```..--`
   .-:///-:::.       `-:::///:-.
      ````.:::`     `:::.````
           -//:`    -::-
            ://:   -::-
            `///- .:::`
             -+++-:::.
              :+/:::-
              `-....`
""")
    