# This file is automatically generated. Please do not modify.

from . import AsciiArt

hash = AsciiArt(match=r'''"Hash"*''', color='123', ascii=r"""
${c1}

      +   ######   +
    ###   ######   ###
  #####   ######   #####
 ######   ######   ######

####### '"###### '"########
#######   ######   ########
#######   ######   ########

 ###### '"###### '"######
  #####   ######   #####
    ###   ######   ###
      ~   ######   ~
""")
    