# This file is automatically generated. Please do not modify.

from . import AsciiArt

hydroos = AsciiArt(match=r'''"HydroOS"*''', color='1 2 3 4 5', ascii=r"""
${c1}
  _    _           _            ____   _____
 | |  | |         | |          / __ \ / ____|
 | |__| |_   _  __| |_ __ ___ | |  | | (___
 |  __  | | | |/ _` | '__/ _ \| |  | |\___ \
 | |  | | |_| | (_| | | | (_) | |__| |____) |
 |_|  |_|\__, |\__,_|_|  \___/ \____/|_____/
          __/ |
         |___/
""")
    