# This file is automatically generated. Please do not modify.

from . import AsciiArt

mac_small = AsciiArt(match=r'''"mac"*"_small"''', color='2 3 1 5 4', ascii=r"""
${c1}       .:'
    _ :'_
${c2} .'`_`-'_``.
:________.-'
${c3}:_______:
:_______:
${c4} :_______`-;
${c5}  `._.-._.'
""")
    