# This file is automatically generated. Please do not modify.

from . import AsciiArt

manjaro_small = AsciiArt(match=r'''"manjaro_small"*''', color='2 7', ascii=r"""
${c1}||||||||| ||||
||||||||| ||||
||||      ||||
|||| |||| ||||
|||| |||| ||||
|||| |||| ||||
|||| |||| ||||
""")
    