# This file is automatically generated. Please do not modify.

from . import AsciiArt

miracle_linux = AsciiArt(match=r'''"MIRACLE LINUX"* | "MIRACLE_LINUX"*''', color='29', ascii=r"""
${c1}            ,A
          .###
     .#' .####   .#.
   r##:  :####   ####.
  +###;  :####  ######C
  :####:  #### ,######".#.
.# :####. :### #####'.#####.
##: `####. ### ###'.########+.
#### `####::## ##'.#######+'
 ####+.`###i## #',####:'
 `+###MI`##### 'l###:'
   `+####+`### ;#E'
      `+###:## #'
         `:### '
           '##
            ';
""")
    