# This file is automatically generated. Please do not modify.

from . import AsciiArt

netbsd_small = AsciiArt(match=r'''"netbsd_small"*''', color='5 7', ascii=r"""
${c2}\\${c1}\`-______,----__
${c2} \\        ${c1}__,---\`_
${c2}  \\       ${c1}\`.____
${c2}   \\${c1}-______,----\`-
${c2}    \\
     \\
      \\
""")
    