# This file is automatically generated. Please do not modify.

from . import AsciiArt

nomadbsd = AsciiArt(match=r'''"NomadBSD"*''', color='4', ascii=r"""
${c1}         _======__
     (===============\
   (===================\
   _              _---__
  (=               ====-
 (=                ======
 (==                ======
 (==                ======
 (==\ \=-_      _=/ /====/
  (==\ \========/ /====/  /====-_
   (==\ \=====/ /==/   /===--
/================/  /===-
\===========/
""")
    