# This file is automatically generated. Please do not modify.

from . import AsciiArt

omnios = AsciiArt(match=r'''"OmniOS"*''', color='15 3 8', ascii=r"""
${c1}
    ____   __  __  _   _  _
   / __ \ |  \/  || \ | || |
  | |  | ||      ||  \| || |
  | |__| || |\/| || , `${c2}_${c1}||${c2}_${c1}|  ${c2}____${c1}
   \____/ |_|  |_||_|\${c2}/ __ \ / ___|
                     | |  | ||(__
         ${c3}community${c2}   | |__| | ___)|
              ${c3}edition${c2} \____/ |____/
""")
    