# This file is automatically generated. Please do not modify.

from . import AsciiArt

openwrt = AsciiArt(match=r'''"OpenWrt"*''', color='4 7 1', ascii=r"""
${c1} _______
|       |.-----.-----.-----.
|   -   ||  _  |  -__|     |
|_______||   __|_____|__|__|
         |__|
 ________        __
|  |  |  |.----.|  |_
|  |  |  ||   _||   _|
|________||__|  |____|
""")
    