# This file is automatically generated. Please do not modify.

from . import AsciiArt

opnsense = AsciiArt(match=r'''"OPNsense"*''', color='7 202', ascii=r"""
${c1}    .'''''''''''''''''''''''''''''''''''
  oocc:::::::::::::::::::::::::::::::cox
 ;00;                                o0O
 .,:'  .;;;;;;;;;;;;;;;;;;;;;;;;;;   ;:,
  .',;;cxOOOOOOOOOOOOOOOOOOOOOOOkd:;;,..
     .,cll:'                 ':llc,.
    ,;;:okxdxd:           :dxdxko:;;,
   .xxxx0XNNK0O.         .O0KNNX0xxxx.
       ,${c2}cc:${c1},.               .,${c2}:cc${c1},
 ........;${c2}ccc:${c1};.         .;${c2}:ccc${c1};........
 ${c2}ccccccccccccccc         ccccccccccccccc${c1}
 ........;${c2}ccc:${c1};.         .;${c2}:ccc${c1};........
       ,${c2}cc:${c1},.               .,${c2}:cc${c1},
   .xxxx0XNNK0O.         .O0KNNX0xxxx.
    ,;;:okxdxd:           :dxdxko:;;,
     .,cll:'                 ':llc,.
  .,,;,ckOOOOOOOOOOOOOOOOOOOOOOOOx;,;,'.
 .:l'  ...........................   ;:;
 lOk'                                cdd
 ;lccccccccccccccccccccccccccccccccccc:.
""")
    