# This file is automatically generated. Please do not modify.

from . import AsciiArt

pisi = AsciiArt(match=r'''"Pisi"*''', color='12 7 6 1 8', ascii=r"""
${c1}   \Fv/!-                      `:?lzC
${c1}   Q!::=zFx!  ${c2}`;v6WBCicl;`  ${c1},vCC\!::#.
${c1}  ,%:::,'` ${c2}+#%@@FQ@@.   ,cF%i${c1}``-',::a?
${c1}  +m:,'```${c2}}3,/@@Q\@@       "af-${c1} `-'"7f
  =o'.` ${c2}/m'   :Q@:Qg         ,kl${c1}  `.|o
  :k` '${c2}$+      'Narm           >d,${c1}  ii
   #`${c2}!p.        `C ,            'd+${c1} %'
${c2}   !0m                           `6Kv
   =a                              m+
  !A     !\L|:            :|L\!     $:
 .8`     Q''%Q#'        '#Q%''Q     `0-
 :6      E|.6QQu        uQQ6.|E      p:
  i{      \jts9?        ?9stj\      u\
   |a`            -''.            `e>
    ,m+     ${c1}'^ !`${c2}s@@@@a${c1}'"`+`${c2}     >e'
      !3|${c1}`|=>>r-  ${c2}'U%:${c1}  '>>>=:`\3!
       'xopE|      ${c2}`'${c1}     `ledoz-
    `;=>>+`${c2}`^llci/|==|/iclc;`${c1}'>>>>:
   `^`+~          ${c2}````${c1}          !!-^
""")
    