# This file is automatically generated. Please do not modify.

from . import AsciiArt

pnm_linux = AsciiArt(match=r'''"PNM Linux"* | "WHPNM Linux"*''', color='33 9 15 202', ascii=r"""

${c1}
               ``.---..` `--`
            ``.---........-:.${c2}-::`${c1}
           ${c2}./::-${c1}........${c2}--::.````${c1}
          ${c2}.:://:::${c1}----${c2}::::-..${c1}
          ..${c2}--:::::--::::++-${c1}.`
  ${c2}`-:-`${c1}   .-ohy+::${c2}-:::${c1}/sdmdd:.${c2}   `-:-
   .-:::${c1}...${c3}sNNmds$y${c1}o/+${c3}sy+NN$m${c1}d+.`${c2}-:::-.
     `.-:-${c1}./${c3}dN${c1}()${c3}yyooosd${c1}()${c3}$m${c1}dy${c2}-.::-.`${c1}
      ${c2}`.${c1}-...-${c3}+hNdyyyyyydmy${c1}:......${c2}`${c1}
 ``..--.....-${c3}yNNm${c4}hssssh${c3}mmdo${c1}.........```
`-:://:.....${c3}hNNNNN${c4}mddm${c3}NNNmds${c1}.....//::--`
  ```.:-...${c3}oNNNNNNNNNNNNNNmd/${c1}...:-.```
      .....${c3}hNNNNNNNNNNNNNNmds${c1}....`
      --...${c3}hNNNNNNNNNNNNNNmdo${c1}.....
      .:...${c3}/NNNNNNNNNNNNNNdd${c1}:....`
       `-...${c3}+mNNNNNNNNNNNmh${c1}:...-.
     ${c4}.:+o+/:-${c1}:+oo+///++o+/:-${c4}:/+ooo/:.
       ${c4}+oo/:o-            +oooooso.`
       ${c4}.`   `             `/  .-//-
""")
    