# This file is automatically generated. Please do not modify.

from . import AsciiArt

postmarketos = AsciiArt(match=r'''"PostMarketOS"*''', color='2 7', ascii=r"""
${c1}                 /\
                /  \
               /    \
              /      \
             /        \
            /          \
            \           \
          /\ \____       \
         /  \____ \       \
        /       /  \       \
       /       /    \    ___\
      /       /      \  / ____
     /       /        \/ /    \
    /       / __________/      \
   /        \ \                 \
  /          \ \                 \
 /           / /                  \
/___________/ /____________________\
""")
    