# This file is automatically generated. Please do not modify.

from . import AsciiArt

puffos = AsciiArt(match=r'''"PuffOS"*''', color='3', ascii=r"""
${c1}
              _,..._,m,
            ,/'      '"";
           /             ".
         ,'mmmMMMMmm.      \
       _/-"^^^^^"\""%#%mm,   ;
 ,m,_,'              "###)  ;,
(###%                 \#/  ;##mm.
 ^#/  __        ___    ;  (######)
  ;  //.\     //.\   ;   \####/
 _; (#\"//     \"/#)  ;  ,/
@##\ \##/   =   `"=" ,;mm/
`\##>.____,...,____,<####@
""")
    