# This file is automatically generated. Please do not modify.

from . import AsciiArt

qubyt = AsciiArt(match=r'''"Qubyt"*''', color='4 5 0 4', ascii=r"""
${c1}    ########################${c2}(${c3}ooo
${c1}    ########################${c2}(${c3}ooo
${c1}###${c2}(${c3}ooo                  ${c1}###${c2}(${c3}ooo
${c1}###${c2}(${c3}ooo                  ${c1}###${c2}(${c3}ooo
${c1}###${c2}(${c3}ooo                  ${c1}###${c2}(${c3}ooo
${c1}###${c2}(${c3}ooo                  ${c1}###${c2}(${c3}ooo
${c1}###${c2}(${c3}ooo                  ${c1}###${c2}(${c3}ooo
${c1}###${c2}(${c3}ooo                  ${c1}###${c2}(${c3}ooo
${c1}###${c2}(${c3}ooo           ${c1}##${c3}o    ${c2}((((${c3}ooo
${c1}###${c2}(${c3}ooo          o${c2}((${c1}###   ${c3}oooooo
${c1}###${c2}(${c3}ooo           oo${c2}((${c1}###${c3}o
${c1}###${c2}(${c3}ooo             ooo${c2}((${c1}###
${c1}################${c2}(${c3}oo    oo${c2}((((${c3}o
${c2}(((((((((((((((((${c3}ooo     ooooo
  oooooooooooooooooo        o
""")
    