# This file is automatically generated. Please do not modify.

from . import AsciiArt

sasanqua = AsciiArt(match=r'''"Sasanqua"*''', color='5 1 5', ascii=r"""
${c1}

                     __,_
             _╕⌐≡µ,√*    º≡,
            ñ     "'       ░
           ╞)         _,   ▒     __
     _,,,_ _Ñ╜^≡µ   ≡'  1µ╕º^el    "%µ
     ∩'     K      Yµ&          1l     ╞)
  ▒     √"        ^Ü          1"     `1µ
  Γ    ║h                  _¿▒∞√;,     ^≡,
   K    ^u_              ⌐*      ╙¥     ╓Ñ
  ⌠        º≡u,,                  ║I    Å
  Ü     _∩"                       ║µ_¿╝"
   Yu_ ▒               ╙º≡_       ║l1µ
      ║l          ,        Y∞µ___≡ª  Γl
       ╓hⁿ╖I     1l         Ñ        ╓Ñ
       Ñ   ¥,___≡1l        ╓Ñ      ¿╕ª
       Ü         ╙L     ¿¿∩ª     ╓P
        ª≡,__      *ⁿ┤ⁿÑⁿ^µ     √ª
              ⁿ≡,,__√╝*    "ⁿⁿ*"
""")
    