# This file is automatically generated. Please do not modify.

from . import AsciiArt

sulin = AsciiArt(match=r'''"Sulin"*''', color='4 7 1', ascii=r"""
${c2}
                         /\          /\
                        ( \\        // )
                         \ \\      // /
                          \_\\||||//_/
                           \/ _  _ \
                          \/|(O)(O)|
                         \/ |      |
     ___________________\/  \      /
    //                //     |____|
   //                ||     /      \
  //|                \|     \ 0  0 /
 // \       )         V    / \____/
//   \     /        (     /
      \   /_________|  |_/
      /  /\   /     |  ||
     /  / /  /      \  ||
     | |  | |        | ||
     | |  | |        | ||
     |_|  |_|        |_||
     \_\  \_\        \_\
""")
    