# This file is automatically generated. Please do not modify.

from . import AsciiArt

sunos = AsciiArt(match=r'''"SunOS"''', color='3 7', ascii=r"""
${c1}                 `-     `
          `--    `+-    .:
           .+:  `++:  -/+-     .
    `.::`  -++/``:::`./+/  `.-/.
      `++/-`.`          ` /++:`
  ``   ./:`                .: `..`.-
``./+/:-                     -+++:-
    -/+`                      :.
""")
    