# This file is automatically generated. Please do not modify.

from . import AsciiArt

trisquel = AsciiArt(match=r'''"Trisquel"*''', color='4 6', ascii=r"""
${c1}                         ,o$$$o.
                      ,o$$Y"\""Y$$b
    ,o$$$$$$o.       ,$$'   ,   Y$$b
 ,o$$$$$$$$$$$$o.    :$      b   Y$$.
,$$"'      "Y$$$$o.   'b.   ,b  d$$$
$$'  .d$$$$b  '$$$$o   'Y$$$Y  d$$$'
$$'  q'    'b  '$$$$$o._   _.o$$$$'
.$$,_    _,d$  ,$$$$$$$$$$$$${c2}$$$$Y'
${c1} '$$$$aaa$$$' .$$$$$$${c2}$$$$$$$$'
${c1}     "\"\""     ${c2}d$$$$"'
             d$$$'   .d$$b.
             $$$$  .$"   'a$.
             $$$$  $b      $$.
             '$$$. '$b,,.  $$$
              '$$$.       .$$'
               'a$$$o._.o$$a'
                  'a$$$$a'
""")
    