# This file is automatically generated. Please do not modify.

from . import AsciiArt

ubuntu_touch = AsciiArt(match=r'''"Ubuntu Touch"*''', color='3 7', ascii=r"""
${c1}
     ###############
   ##               ##
  ##  ${c2}##${c1}         ${c2}##${c1}  ##
  ##  ${c2}##${c1}  ${c2}#${c1}   ${c2}#${c1}  ${c2}##${c1}  ##
  ##       ${c2}###${c1}       ##
   ##               ##
     ###############
""")
    