# This file is automatically generated. Please do not modify.

from . import AsciiArt

uos = AsciiArt(match=r'''"Uos"*''', color='1 7 3', ascii=r"""
${c1}
                        .......
                    ..............
                ......................
             .............................
  uuuuuu    uuuuuu     ooooooooooo       ssssssssss
  u::::u    u::::u   oo:::::::::::oo   ss::::::::::s
  u::::u    u::::u  o:::::::::::::::oss:::::::::::::s
  u::::u    u::::u  o:::::ooooo:::::os::::::ssss:::::s
  u::::u    u::::u  o::::o     o::::o s:::::s  ssssss
  u::::u    u::::u  o::::o     o::::o   s::::::s
  u::::u    u::::u  o::::o     o::::o      s::::::s
  u:::::uuuu:::::u  o::::o     o::::ossssss   s:::::s
  u:::::::::::::::uuo:::::ooooo:::::os:::::ssss::::::s
  u:::::::::::::::uo:::::::::::::::os::::::::::::::s
  uu::::::::uu:::u oo:::::::::::oo  s:::::::::::ss
      uuuuuuuu  uuuu   ooooooooooo     sssssssssss
            .............................
                .....................
                    .............
                        ......
""")
    