# This file is automatically generated. Please do not modify.

from . import AsciiArt

vnux = AsciiArt(match=r'''"VNux"*''', color='11 8 15 1 7', ascii=r"""
${c1}              `
           ^[XOx~.
        ^_nwdbbkp0ti'
        <vJCZw0LQ0Uj>
${c2}          _j>!vC1,,
     ${c4},${c2}   ,CY${c3}O${c2}t${c3}O${c2}1(l;"
`${c4}~-{r(1I${c2} ^${c1}/zmwJuc:${c2}I^
'${c4}?)|${c1}U${c4}/}-${c2} ^${c3}f${c1}OCLLOw${c3}_${c2},;
 ,${c4}i,``. ${c2}",${c3}k%ooW@$d"${c2}I,'
  '    ;^${c3}u$$$$$$$$^<${c2}:^
   ` .>>${c3}($$${c5}$@@@@$$${c3}$nl${c2}[::
    `!}?${c3}B$${c5}%&WMMW&%$${c3}$1}-${c2}}":
    ^?j${c3}Z$${c5}WMMWWWWMMW$${c3}ofc${c2};;`
    <~x&${c3}$${c5}&MWWWWWWWWp${c3}-${c5}l>[<
${c1} 'ljmwn${c2}~tk8${c5}MWWWWM8O${c2}X${c1}r${c2}+]nC${c1}[
!JZqwwdX${c2}:^C8${c5}#MMMM@${c2}X${c1}Odpdpq0<
<wwwwmmpO${c2}1${c3}0@%%%%8${c2}d${c1}nqmwmqqqJl
?QOZmqqqpb${c2}t[run/?!${c1}0pwqqQj-,
 ^:l<{nUUv>      ^x00J("
                   ^"
""")
    