# This file is automatically generated. Please do not modify.

from . import AsciiArt

wii_linux_ngx = AsciiArt(match=r'''*"wii-linux-ngx"*|*"whiite-linux"*|         *"gc-linux"*''', color='6 7', ascii=r"""
${c1}'''''''            `~;:`            -''''''   ~kQ@@g\      ,EQ@@g/
h@@@@@@'          o@@@@@9`         `@@@@@@D  `@@@@@@@=     @@@@@@@?
'@@@@@@X         o@@@@@@@D         v@@@@@@:   R@@@@@@,     D@@@@@@_
 t@@@@@@'       _@@@@@@@@@;       `Q@@@@@U     ;fmo/-       ;fmo/-
 `Q@@@@@m       d@@@@@@@@@N       7@@@@@@'
  L@@@@@@'     :@@@@@&@@@@@|     `Q@@@@@Z     :]]]]]v      :]]]]]v
   Q@@@@@X     R@@@@Q`g@@@@Q     f@@@@@Q-     z@@@@@Q      v@@@@@Q
   r@@@@@@~   ;@@@@@/ ;@@@@@L   `@@@@@@/      z@@@@@Q      v@@@@@Q
    d@@@@@q   M@@@@#   H@@@@Q   ]@@@@@Q       z@@@@@Q      v@@@@@Q
    ,@@@@@@, >@@@@@;   _@@@@@c `@@@@@@>       z@@@@@Q      v@@@@@Q
     X@@@@@U Q@@@@R     Z@@@@Q`{@@@@@N        z@@@@@Q      v@@@@@Q
     .@@@@@@S@@@@@:     -@@@@@e@@@@@@:        z@@@@@Q      v@@@@@Q
      {@@@@@@@@@@U       t@@@@@@@@@@e         z@@@@@Q      v@@@@@Q
      `Q@@@@@@@@@'       `Q@@@@@@@@@-         z@@@@@Q      v@@@@@Q
       :@@@@@@@@|         ;@@@@@@@@=          z@@@@@Q      v@@@@@Q
        '2#@@Q6:           ,eQ@@QZ~           /QQQQQg      \QQQQQN
""")
    