#!/usr/bin/env bash
#
# Neofetch config file
# https://github.com/dylanaraps/neofetch

# Speed up script by not using unicode
export LC_ALL=C
export LANG=C


# See this wiki page for more info:
# https://github.com/dylanaraps/neofetch/wiki/Customizing-Info
print_info() {
    info title
    info underline

    info "OS" distro
    info "Model" model
    info "Kernel" kernel
    info "Uptime" uptime
    info "Packages" packages
    info "Shell" shell
    info "Resolution" resolution
    info "DE" de
    info "WM" wm
    info "WM Theme" wm_theme
    info "Theme" theme
    info "Icons" icons
    info "Terminal" term
    info "Terminal Font" term_font
    info "CPU" cpu
    info "GPU" gpu
    info "Memory" memory

    # info "CPU Usage" cpu_usage
    # info "Disk" disk
    # info "Battery" battery
    # info "Font" font
    # info "Song" song
    # info "Local IP" local_ip
    # info "Public IP" public_ip
    # info "Users" users
    # info "Birthday" birthday

    info line_break
    info cols
    info line_break
}


# Kernel


# Shorten the output of the kernel function
# --kernel_shorthand on, off
kernel_shorthand="on"


# Distro


# Shorten the output of the distro function
# NOTE: This is only possible on Linux, macOS, and Solaris
# --distro_shorthand on, off, tiny
distro_shorthand="off"

# Show 'x86_64' and 'x86' in 'Distro:' output.
# --os_arch on, off
os_arch="on"


# Uptime


# Shorten the output of the uptime function
# --uptime_shorthand tiny, on, off
uptime_shorthand="off"


# Shell


# Show the path to $SHELL
# --shell_path on, off
shell_path="off"

# Show $SHELL version
# --shell_version on, off
shell_version="on"


# CPU


# CPU speed type
# Only works on Linux with cpufreq.
# --speed_type current, min, max, bios,
# scaling_current, scaling_min, scaling_max
speed_type="max"

# Shorten the output of the CPU function
# --cpu_shorthand name, speed, tiny, on, off
cpu_shorthand="off"

# CPU Usage display
# Set CPU usage display setting
# --cpu_display bar, infobar, barinfo, off
cpu_display="off"

# CPU Speed
# Hide/Show CPU speed.
# --cpu_speed on, off
cpu_speed="on"

# CPU Cores
# Display CPU cores in output
# Logical: All virtual cores
# Physical: All physical cores
# Note: 'physical' doesn't work on BSD.
# --cpu_cores logical, physical, off
cpu_cores="logical"

# CPU Temperature
# Hide/Show CPU temperature.
# Note: Only works on Linux.
# --cpu_temp on, off
cpu_temp="off"


# GPU


# Enable/Disable GPU Brand
# --gpu_brand on, off
gpu_brand="on"


# Resolution


# Display refresh rate next to each monitor
# Unsupported on Windows
# --refresh_rate on, off
refresh_rate="off"


# Gtk Theme / Icons


# Shorten output (Hide [GTK2] etc)
# --gtk_shorthand on, off
gtk_shorthand="off"


# Enable/Disable gtk2 theme/icons output
# --gtk2 on, off
gtk2="on"

# Enable/Disable gtk3 theme/icons output
# --gtk3 on, off
gtk3="on"


# IP Address


# Website to ping for the public IP
# --ip_host url
public_ip_host="http://ident.me"


# Song


# Print the Artist and Title on seperate lines
# --song_shorthand on, off
song_shorthand="off"


# Birthday


# Whether to show a long pretty output
# or a shortened one
# NOTE: Long pretty output doesn't work on OpenBSD or NetBSD.
# --birthday_shorthand on, off
birthday_shorthand="off"

# Whether to show the time in the output
# --birthday_time on, off
birthday_time="on"

# Date format to use when printing birthday
# --birthday_format "format"
birthday_format="+%a %d %b %Y %l:%M %p"


# Text Colors


# Text Colors
# Each number represents a different part of
# the text in this order:
# title, @, underline, subtitle, colon, info
# colors=(4 6 1 8 8 6)
# You can also specify:
# fg (foreground color)
colors=(distro)


# Text Options


# Toggle bold text
# --bold on, off
bold="on"

# Enable/Disable Underline
# --underline on, off
underline_enabled="on"

# Underline character
# --underline_char char
underline_char="-"


# Color Blocks


# Color block range
# --block_range start end
start=0
end=7

# Toggle color blocks
# --color_blocks on, off
color_blocks="on"

# Color block width in spaces
# --block_width num
block_width=3

# Color block height in lines
# --block_height num
block_height=1


# Progress Bars


# Progress bar character
# --progress_char elapsed_char total_char
bar_char_elapsed="-"
bar_char_total="="

# Progress border
# --progress_border on, off
bar_border="on"

# Progress bar length in spaces
# Number of chars long to make the progress bars.
# --progress_length num
bar_length="15"

# Progress bar colors
# When set to distro, uses your distro's logo colors
# Takes: num, "distro"
# --progress_colors col col
bar_color_elapsed="distro"
bar_color_total="distro"

# Customize how the info is displayed.
# bar: Only the progress bar is displayed.
# infobar: The bar is displayed after the info.
# barinfo: The bar is displayed before the info.
# off: Only the info is displayed.
#
# --memory_display bar, infobar, barinfo, off
# --battery_display bar, infobar, barinfo, off
# --disk_display bar, infobar, barinfo, off
memory_display="off"
battery_display="off"
disk_display="off"


# Image Options


# Image Source
# --image wallpaper, /path/to/img, /path/to/dir/, off
image_source="wallpaper"

# Thumbnail directory
thumbnail_dir="${XDG_CACHE_HOME:-${HOME}/.cache}/thumbnails/neofetch"

# W3m-img path
# Only works with the w3m backend.
#
# NOTE: Only change this if "neofetch -v" says that it couldn't find w3m-img.
# Neofetch has a function that automatically finds w3m-img for you. It looks
# in the following directories:
#    /usr/lib/w3m/w3mimgdisplay
#    /usr/libexec/w3m/w3mimgdisplay
#    /usr/lib64/w3m/w3mimgdisplay
#    /usr/libexec64/w3m/w3mimgdisplay
# If w3m-img is installed elsewhere on your system, open an issue on the repo
# and I'll add it to the function inside the script. If w3m-img is installed
# in a non-standard way (in your home folder, etc) then change the variable
# below to the custom location. Otherwise, don't touch this.
w3m_img_path="/usr/lib/w3m/w3mimgdisplay"

# Crop mode
# --crop_mode normal, fit, fill
crop_mode="normal"

# Crop offset
# Only affects normal mode.
# --crop_offset northwest, north, northeast, west, center
#               east, southwest, south, southeast
crop_offset="center"

# Image size
# The image is half the terminal width by default.
# --size auto, 00px, 00%, none
image_size="auto"

# Right gap between image and text
# --gap num
gap=3

# Image offsets
# Only works with the w3m backend.
# --xoffset px
# --yoffset px
yoffset=0
xoffset=0

# Image background color
# Only works with the w3m backend.
# Unset by default.
# --bg_color 'color', blue
background_color=


# Ascii Options


# Default ascii image to use
# When this is set to distro it will use your
# distro's logo as the ascii.
# --ascii 'distro', path/to/ascii
ascii="distro"

# Ascii distro
# Which distro's ascii art to display.
# --ascii_distro 'auto', 'distro_name'
ascii_distro="auto"

# Ascii colors
# When this is set to distro it will use your
# ditro's colors to color the ascii.
# NOTE: You can also set this to a range of colors
# which will allow you to custom color distro logos
# --ascii_colors distro
# --ascii_colors 2 4 5 6
ascii_colors=(distro)

# Logo size
# Arch, Crux and Gentoo have a smaller logo
# variant. Changing the value below to small
# will make neofetch use the small logo.
# --ascii_logo_size small, normal
ascii_logo_size="normal"

# Bold ascii logo
# Whether or not to bold the ascii logo.
# --ascii_bold on, off
ascii_bold="on"


# Scrot Options


# Whether or not to always take a screenshot
# You can manually take a screenshot with "--scrot" or "-s"
scrot="off"

# Screenshot program to launch
# --scrot_cmd
scrot_cmd="scrot -c -d 3"

# Scrot dir
# Where to save the screenshots
# --scrot_dir /path/to/screenshot/folder
scrot_dir="$HOME/Pictures/"

# Scrot filename
# What to name the screenshots
# --scrot_name str
scrot_name="neofetch-$(date +%F-%I-%M-%S-${RANDOM}).png"

# Image upload host
# Where to upload the image.
# Possible values: imgur, teknik
image_host="imgur"


# Config Options


# Enable/Disable config file
# --config off, none
config="on"

# Path to custom config file location
# --config path/to/config
config_file="${XDG_CONFIG_HOME:-${HOME}/.config}/neofetch/config"
