#!/usr/bin/env bash
# vim:fdm=marker
#
# Neofetch config file for travis.ci
# https://github.com/dylanaraps/neofetch

printinfo() {
    if [ "$TRAVIS_OS_NAME" ]; then
        linebreak
        linebreak
    fi

    title
    underline

#   Function    Subtitle
    model       "Model"
    distro      "OS"
    kernel      "Kernel"
    uptime      "Uptime"
    packages    "Packages"
    shell       "Shell"
    resolution  "Resolution"
    de          "DE"
    wm          "WM"
    wmtheme     "WM Theme"
    theme       "Theme"
    icons       "Icons"
    term        "Terminal"
    termfont    "Terminal Font"
    cpu         "CPU"
    gpu         "GPU"
    memory      "Memory"

# Remove the '#' to enable these
    cpu_usage   "CPU Usage"
    disk        "Disk"
    battery     "Battery"
    font        "Font"
    song        "Song"
    localip     "Local IP"
    publicip    "Public IP"
    users       "Users"
    birthday    "Birthday"

    linebreak
    cols
    linebreak
}

refresh_rate="on"
shell_version="on"
cpu_display="infobar"
memory_display="infobar"
disk_display="infobar"
cpu_temp="on"
