#!/usr/bin/env bash
getcols () {
    if [ "$color_blocks" == "on" ]; then
        printf "${padding}%s"
        while [ $start -le $end ]; do
            case "$start" in
                [0-6]) printf "\033[4${start}m%${block_width}s" ;;
                7) printf "\033[4${start}m%${block_width}s${clear}\n${padding}" ;;
                *) printf "\033[48;5;${start}m%${block_width}s" ;;
            esac
            start=$((start + 1))
        done

        # Clear formatting
        printf "%b%s" "$clear"
    fi
}
