#!/usr/bin/env bash
# vim: fdm=marker:noai:ts=4:sw=4
#
# Neofetch CPU usage detection.

getcpu_usage () {
    case "$os" in
        "Windows")
            cpu_usage="$(wmic cpu get loadpercentage /value)"
            cpu_usage="${cpu_usage/LoadPercentage'='}"
            cpu_usage="${cpu_usage//[[:space:]]}"
        ;;

        "Linux" | "Mac OS X" | "iPhone OS" | "BSD")
            # Get cores if unset
            if [ -z "$cores" ]; then
                case "$os" in
                    "Linux") cores="$(awk -F ': ' '/siblings/ {printf $2; exit}' /proc/cpuinfo)" ;;
                    "Mac OS X" | "BSD") cores="$(sysctl -n hw.ncpu)" ;;
                esac
            fi

            cpu_usage="$(ps aux | awk 'BEGIN {sum=0} {sum+=$3 }; END {print sum}')"
            cpu_usage="$((${cpu_usage/\.*} / ${cores:-1}))"
        ;;
    esac

    # Print the bar
    case "$cpu_display" in
        "info") cpu_usage="${cpu_usage}%" ;;
        "bar") cpu_usage="$(bar $cpu_usage 100)" ;;
        "infobar") cpu_usage="${cpu_usage}% $(bar $cpu_usage 100)" ;;
        "barinfo") cpu_usage="$(bar $cpu_usage 100) ${cpu_usage}%" ;;
    esac
}
