#!/usr/bin/env bash
getde () {
    case "$os" in
        "Mac OS X") de="Aqua" ;;
        *)
            de="${XDG_CURRENT_DESKTOP/i3}"
            de=${de/'X-'}
        ;;
    esac

    if [ -n "$DISPLAY" ] && [ -z "$de" ]; then
        de="$(xprop -root | awk '/KDE_SESSION_VERSION|^_MARCO|^_MUFFIN|xfce4|xfce5/' 2>/dev/null)"

        case "$de" in
            "KDE_SESSION_VERSION"*) de="KDE${de/* = }" ;;
            *"MUFFIN"*) de="Cinnamon" ;;
            *"MARCO"*) de="MATE" ;;
            *"xfce4"*) de="XFCE4" ;;
            *"xfce5"*) de="XFCE5" ;;
        esac
    fi
}
