#!/usr/bin/env bash
getstyle () {
    # Fix weird output when the function
    # is run multiple times.
    unset gtk2theme gtk3theme theme path

    case "$1" in
        theme)
            name="gtk-theme-name"
            gsettings="gtk-theme"
            gconf="gtk_theme"
            xfconf="ThemeName"
            kde="widgetStyle"
        ;;

        icons)
            name="gtk-icon-theme-name"
            gsettings="icon-theme"
            gconf="icon_theme"
            xfconf="IconThemeName"
            kde="Theme"
        ;;

        font)
            name="gtk-font-name"
            gsettings="font-name"
            gconf="font_theme"
            xfconf="FontName"
            kde="font"
        ;;
    esac

    if [ -n "$DISPLAY" ] && [ "$os" != "Mac OS X" ]; then
        # Get DE if user has disabled the function.
        [ -z "$de" ] && getde

        case "$de" in
            "KDE"*)
                kdeconfigdir

                if [ -f "${kde_config_dir}/share/config/kdeglobals" ]; then
                    kde_config_file="${kde_config_dir}/share/config/kdeglobals"

                    theme=$(grep "^[^#]*$kde" "$kde_config_file")
                    theme=${theme/${kde}*=}
                    [ "$version" -ge 4 ] && theme=${theme^}

                    gtk_shorthand="on"
                    return
                fi
            ;;

            *"Cinnamon")
                if type -p gsettings >/dev/null 2>&1; then
                    gtk3theme=$(gsettings get org.cinnamon.desktop.interface $gsettings)
                    gtk3theme=${gtk3theme//"'"}
                    gtk2theme=${gtk3theme}
                fi
            ;;

            "Gnome"* | "Unity"* | "Budgie")
                if type -p gsettings >/dev/null 2>&1; then
                    gtk3theme=$(gsettings get org.gnome.desktop.interface $gsettings)
                    gtk3theme=${gtk3theme//"'"}
                    gtk2theme=${gtk3theme}

                elif type -p gconftool-2 >/dev/null 2>&1; then
                    gtk2theme=$(gconftool-2 -g /desktop/gnome/interface/$gconf)
                fi
            ;;

            "Mate"*)
                gtk3theme=$(gsettings get org.mate.interface $gsettings)
                gtk2theme=${gtk3theme}
            ;;

            "Xfce"*)
                type -p xfconf-query >/dev/null 2>&1 && \
                    gtk2theme=$(xfconf-query -c xsettings -p /Net/$xfconf)
            ;;
        esac

        # Check for gtk2 theme
        if [ -z "$gtk2theme" ]; then
            if [ -f "${GTK2_RC_FILES:-$HOME/.gtkrc-2.0}" ]; then
                gtk2theme=$(grep "^[^#]*$name" "${GTK2_RC_FILES:-$HOME/.gtkrc-2.0}")

            elif [ -f "/usr/share/gtk-2.0/gtkrc" ]; then
                gtk2theme=$(grep "^[^#]*$name" /usr/share/gtk-2.0/gtkrc)

            elif [ -f "/etc/gtk-2.0/gtkrc" ]; then
                gtk2theme=$(grep "^[^#]*$name" /etc/gtk-2.0/gtkrc)
            fi

            gtk2theme=${gtk2theme/${name}*=}
            gtk2theme=${gtk2theme//\"}
        fi

        # Check for gtk3 theme
        if [ -z "$gtk3theme" ]; then
            if [ -f "$XDG_CONFIG_HOME/gtk-3.0/settings.ini" ]; then
                gtk3theme=$(grep "^[^#]*$name" "$XDG_CONFIG_HOME/gtk-3.0/settings.ini")

            elif type -p gsettings >/dev/null 2>&1; then
                gtk3theme="$(gsettings get org.gnome.desktop.interface $gsettings)"
                gtk3theme=${gtk3theme//\'}

            elif [ -f "/usr/share/gtk-3.0/settings.ini" ]; then
                gtk3theme=$(grep "^[^#]*$name" /usr/share/gtk-3.0/settings.ini)

            elif [ -f "/etc/gtk-3.0/settings.ini" ]; then
                gtk3theme=$(grep "^[^#]*$name" /etc/gtk-3.0/settings.ini)
            fi

            gtk3theme=${gtk3theme/${name}*=}
            gtk3theme=${gtk3theme//\"}
            gtk3theme=${gtk3theme/[[:space:]]/ }
        fi

        # Uppercase the first letter of each gtk theme
        if [ "$version" -ge 4 ]; then
            gtk2theme=${gtk2theme^}
            gtk3theme=${gtk3theme^}
        fi

        # Toggle visibility of gtk themes.
        [ "$gtk2" == "off" ] && unset gtk2theme
        [ "$gtk3" == "off" ] && unset gtk3theme

        # Format the string based on which themes exist
        if  [ "$gtk2theme" ] && [ "$gtk2theme" == "$gtk3theme" ]; then
            gtk3theme+=" [GTK2/3]"
            unset gtk2theme

        elif [ "$gtk2theme" ] && [ "$gtk3theme" ]; then
            gtk2theme+=" [GTK2], "
            gtk3theme+=" [GTK3] "
        else
            [ "$gtk2theme" ] && gtk2theme+=" [GTK2] "
            [ "$gtk3theme" ] && gtk3theme+=" [GTK3] "
        fi

        # Final string
        theme="${gtk2theme}${gtk3theme}"
        theme=${theme//\"}
        theme=${theme//\'}

        # Make the output shorter by removing "[GTKX]" from the string
        if [ "$gtk_shorthand" == "on" ]; then
            theme=${theme/ '[GTK2]'}
            theme=${theme/ '[GTK3]'}
            theme=${theme/ '[GTK2/3]'}
        fi
    fi
}

gettheme () {
    getstyle theme
}

geticons () {
    getstyle icons
    icons="$theme"
}

getfont () {
    getstyle font
    font="$theme"
}
